apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/managed-by: cloudnative-pg
    cnpg.io/cluster: postgres
    cnpg.io/reload: 'true'
    cnpg.io/userType: superuser
  name: postgres-credentials
  namespace: cnpg
type: kubernetes.io/basic-auth
data:
  dbname: Kg==
  fqdn-jdbc-uri: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcncuY25wZy5zdmMuY2x1c3Rlci5sb2NhbDo1NDMyLyo/cGFzc3dvcmQ9dGhlZWFnbGVmbGllc2F0bWlkbmlnaHQmdXNlcj1wb3N0Z3Jlcw==
  fqdn-uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRoZWVhZ2xlZmxpZXNhdG1pZG5pZ2h0QHBvc3RncmVzLXJ3LmNucGcuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi8q
  host: cG9zdGdyZXMtcnc=
  jdbc-uri: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcncuY25wZzo1NDMyLyo/cGFzc3dvcmQ9dGhlZWFnbGVmbGllc2F0bWlkbmlnaHQmdXNlcj1wb3N0Z3Jlcw==
  password: dGhlZWFnbGVmbGllc2F0bWlkbmlnaHQ=
  pgpass: cG9zdGdyZXMtcnc6NTQzMjoqOnBvc3RncmVzOnRoZWVhZ2xlZmxpZXNhdG1pZG5pZ2h0XG4=
  port: NTQzMg==
  uri: cG9zdGdyZXNxbDovL3Bvc3RncmVzOnRoZWVhZ2xlZmxpZXNhdG1pZG5pZ2h0QHBvc3RncmVzLXJ3LmNucGc6NTQzMi8q
  user: cG9zdGdyZXM=
  username: cG9zdGdyZXM=
